apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-meta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadb-app
  template:
    metadata:
      labels:
        app: metadb-app
    spec:               #What state you desire for the object
      containers:
      - name: metadb-container
        image: metadatabase:db
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /meta-data
            name: practicum-1-meta-data-volume
        volumes:
          - name: practicum-1-meta-data-volume
            persistentVolumeClain:
              claimName: practicum-1-meta-data-claim
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
    name: webapp-meta-db-service
spec:
    selector:
        app: metadb-app
    ports:
      - protocol: TCP
        port: 8082
        targetPort: 8082
