apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-get-image-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-container
        image: frontend:fe
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /image-data
            name: practicum-1-images-volume
        volumes:
          - name: practicum-1-images-volume
            persistentVolumeClain:
              claimName: practicum-1-images-disk-read-claim
        env:
        - name: DB_HOST1
          valueFrom:
              configMapKeyRef:
                  name: webappdb-configmap  # 🎃 must match
                  key: meta_database_host
        - name: DB_HOST2
          valueFrom:
              configMapKeyRef:
                  name: webappdb-configmap  # 🎃 must match
                  key: similarity_database_host
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: webapp-frontend-service
spec:
    selector:
        app: frontend-app
    type: LoadBalancer  #We want this exposed to the outside world
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
        nodePort: 30000
