# gcePersistentDisk - Persistent Volume and Persistent Volume Claim
apiVersion: v1
kind: PersistentVolume
metadata:
  name: practicum1-meta-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  gcePersistentDisk:
    pdName: practicum-1-meta-data
    fsType: ext4
    readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: practicum-1-meta-data-claim
spec:
  resources:
      requests:
        storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: ""

